spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.199.194:3306/FcNetworkSite?useUnicode=true&characterEncoding=utf8
    username: 'root'
    password: '090448'
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fido.fcnetworksite.entity  # 注意：对应实体类的路径
server:
  servlet:
    context-path: "/fcnetworksite"
