spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.199.194:3306/FcNetworkSite?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: 'root'
    password: '090448'
  redis:
    password:
    database: 0
    port: 6379
    host: 47.106.199.194
    timeout: 5000
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fido.fcnetworksite.entity  # 注意：对应实体类的路径
server:
  context-path: "/fcnetworksite"
  port: 8060

pagehelper:
  helperDialect=mysql
  reasonable=true

# 打印sql
logging:
  level:
    com.onepro.custom.mapper: DEBUG